---
- name: Provision VM via Terraform (Proxmox)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Terraform | Init
      command: terraform init -input=false
      args:
        chdir: "{{ playbook_dir }}"

    - name: Terraform | Apply
      command: terraform apply -auto-approve -input=false
      args:
        chdir: "{{ playbook_dir }}"

    - name: Terraform | Output (JSON)
      command: terraform output -json
      args:
        chdir: "{{ playbook_dir }}"
      register: tf_out
      failed_when: false

    - name: Show outputs
      debug:
        var: tf_out.stdout
